In [3]:

from pathlib import Path

print("Current notebook folder:")
print(Path.cwd())

print("\nCSV files found in the current folder and its subfolders:")

for file in Path.cwd().parent.rglob("*.csv"):
    print(file)

Current notebook folder:
c:\Users\k\Desktop\KPI-Data-Quality-Project\src

CSV files found in the current folder and its subfolders:
c:\Users\k\Desktop\KPI-Data-Quality-Project\data\retail-data-dictionary.csv
c:\Users\k\Desktop\KPI-Data-Quality-Project\data\retail-orders-raw.csv

In [4]:

import pandas as pd
from pathlib import Path

# Go from the src folder to the main project folder
PROJECT_DIR = Path.cwd().parent
data_dir = PROJECT_DIR / "data"

print("Looking for files in:", data_dir)

orders_file = data_dir / "retail-orders-raw.csv"
dictionary_file = data_dir / "retail-data-dictionary.csv"

print("Orders file exists:", orders_file.exists())
print("Dictionary file exists:", dictionary_file.exists())

if orders_file.exists() and dictionary_file.exists():
    orders = pd.read_csv(orders_file)
    dictionary = pd.read_csv(dictionary_file)

    print("\nOrders dataset shape:", orders.shape)
    print("Dictionary shape:", dictionary.shape)

    print("\nColumn names:")
    print(orders.columns.tolist())

    print("\nFirst 5 rows of orders:")
    display(orders.head())

    print("\nData dictionary:")
    display(dictionary.head())
else:
    print("\nFiles not found. Check that both CSV files are inside:")
    print(data_dir)

Looking for files in: c:\Users\k\Desktop\KPI-Data-Quality-Project\data
Orders file exists: True
Dictionary file exists: True

Orders dataset shape: (12, 9)
Dictionary shape: (9, 4)

Column names:
['order_id', 'order_date', 'customer_segment', 'city', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_status']

First 5 rows of orders:

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03/01/2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid

Data dictionary:

,column,data_type,business_definition,quality_rule
0,order_id,string,Unique order identifier,Required and unique
1,order_date,date,Date the customer placed the order,Required ISO date between 2025-01-01 and today
2,customer_segment,category,Commercial customer segment,Student Fresher or Professional after normaliz...
3,city,string,Customer billing city,Required non-empty text
4,category,category,Product family,Learning Kit Course Access or Mentor Session

In [5]:

# Basic data profiling

print("DATA TYPES")
display(orders.dtypes.to_frame("Data Type"))

print("\nMISSING VALUES")
missing = orders.isnull().sum().to_frame("Missing Values")
missing["Missing Percentage"] = (
    orders.isnull().mean() * 100
).round(2)
display(missing)

print("\nDUPLICATE ROWS")
print("Duplicate rows:", orders.duplicated().sum())

print("\nUNIQUE VALUES")
display(orders.nunique().to_frame("Unique Values"))

print("\nNUMERIC SUMMARY")
display(orders.describe(include="number").T)

print("\nDATA QUALITY SUMMARY")
print("Total rows:", len(orders))
print("Total columns:", len(orders.columns))
print("Total missing cells:", int(orders.isnull().sum().sum()))
print("Total duplicate rows:", int(orders.duplicated().sum()))

DATA TYPES

                 Data Type
order_id            object
order_date          object
customer_segment    object
city                object
category            object
quantity            object
unit_price           int64
discount_pct       float64
payment_status      object

MISSING VALUES

                  Missing Values  Missing Percentage
order_id                       0                0.00
order_date                     1                8.33
customer_segment               0                0.00
city                           1                8.33
category                       0                0.00
quantity                       0                0.00
unit_price                     0                0.00
discount_pct                   1                8.33
payment_status                 0                0.00

DUPLICATE ROWS
Duplicate rows: 1

UNIQUE VALUES

                  Unique Values
order_id                     11
order_date                   10
customer_segment              4
city                          7
category                      3
quantity                      5
unit_price                    3
discount_pct                  5
payment_status                5

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
unit_price,12.0,1082.333333,318.614425,799.0,799.0,999.0,1499.0,1499.0
discount_pct,11.0,13.636364,30.748245,0.0,0.0,5.0,10.0,105.0

DATA QUALITY SUMMARY
Total rows: 12
Total columns: 9
Total missing cells: 3
Total duplicate rows: 1

In [6]:

import pandas as pd
from pathlib import Path

# Locate the main project folder
PROJECT_DIR = Path.cwd().parent

# Load the datasets
data_dir = PROJECT_DIR / "data"

orders_file = data_dir / "retail-orders-raw.csv"
dictionary_file = data_dir / "retail-data-dictionary.csv"

print("Orders file exists:", orders_file.exists())
print("Dictionary file exists:", dictionary_file.exists())

if not orders_file.exists() or not dictionary_file.exists():
    raise FileNotFoundError(
        "Check that both CSV files are inside the project's data folder."
    )

orders = pd.read_csv(orders_file)
dictionary = pd.read_csv(dictionary_file)

print("\nDATASET OVERVIEW")
print("Number of rows:", orders.shape[0])
print("Number of columns:", orders.shape[1])

print("\nCOLUMN NAMES")
print(orders.columns.tolist())

print("\nFIRST FIVE ROWS")
display(orders.head())

print("\nDATA DICTIONARY")
display(dictionary.head())

print("\nMISSING VALUES")
missing = pd.DataFrame({
    "Missing Count": orders.isnull().sum(),
    "Missing Percentage": (orders.isnull().mean() * 100).round(2)
})
display(missing)

print("\nDUPLICATE ROWS")
print("Duplicate rows:", orders.duplicated().sum())

print("\nDATA TYPES")
display(orders.dtypes.to_frame("Data Type"))

print("\nUNIQUE VALUES")
display(orders.nunique().to_frame("Unique Values"))

print("\nNUMERIC SUMMARY")
display(orders.describe(include="number").T)

Orders file exists: True
Dictionary file exists: True

DATASET OVERVIEW
Number of rows: 12
Number of columns: 9

COLUMN NAMES
['order_id', 'order_date', 'customer_segment', 'city', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_status']

FIRST FIVE ROWS

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03/01/2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid

DATA DICTIONARY

,column,data_type,business_definition,quality_rule
0,order_id,string,Unique order identifier,Required and unique
1,order_date,date,Date the customer placed the order,Required ISO date between 2025-01-01 and today
2,customer_segment,category,Commercial customer segment,Student Fresher or Professional after normaliz...
3,city,string,Customer billing city,Required non-empty text
4,category,category,Product family,Learning Kit Course Access or Mentor Session

MISSING VALUES

                  Missing Count  Missing Percentage
order_id                      0                0.00
order_date                    1                8.33
customer_segment              0                0.00
city                          1                8.33
category                      0                0.00
quantity                      0                0.00
unit_price                    0                0.00
discount_pct                  1                8.33
payment_status                0                0.00

DUPLICATE ROWS
Duplicate rows: 1

DATA TYPES

                 Data Type
order_id            object
order_date          object
customer_segment    object
city                object
category            object
quantity            object
unit_price           int64
discount_pct       float64
payment_status      object

UNIQUE VALUES

                  Unique Values
order_id                     11
order_date                   10
customer_segment              4
city                          7
category                      3
quantity                      5
unit_price                    3
discount_pct                  5
payment_status                5

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
unit_price,12.0,1082.333333,318.614425,799.0,799.0,999.0,1499.0,1499.0
discount_pct,11.0,13.636364,30.748245,0.0,0.0,5.0,10.0,105.0

In [7]:

# DATA QUALITY CONTRACT: EXECUTABLE CHECKS

import pandas as pd
from datetime import date

df = orders.copy()

# Normalize text for validation without changing original data
segments = df["customer_segment"].astype("string").str.strip().str.title()
categories = df["category"].astype("string").str.strip().str.title()
payments = df["payment_status"].astype("string").str.strip().str.title()

# Parse dates for validation
parsed_dates = pd.to_datetime(
    df["order_date"], format="mixed", dayfirst=False, errors="coerce"
)

checks = []

def add_check(name, failed_rows, total_rows, rule):
    failed_count = int(failed_rows.sum())
    checks.append({
        "Quality Check": name,
        "Failed Rows": failed_count,
        "Total Rows": total_rows,
        "Pass Rate (%)": round(
            (total_rows - failed_count) / total_rows * 100, 2
        ) if total_rows else 100.0,
        "Rule": rule
    })

n = len(df)

# 1. Completeness
add_check(
    "Missing Order ID",
    df["order_id"].isna() | df["order_id"].astype("string").str.strip().eq(""),
    n, "Order ID must not be missing"
)

add_check(
    "Missing City",
    df["city"].isna() | df["city"].astype("string").str.strip().eq(""),
    n, "City must not be empty"
)

# 2. Uniqueness
add_check(
    "Duplicate Order ID",
    df["order_id"].duplicated(keep=False),
    n, "Order ID must be unique according to the data dictionary"
)

# 3. Date validity
add_check(
    "Invalid Date Format or Value",
    parsed_dates.isna() |
    ~df["order_date"].astype("string").str.fullmatch(r"\d{4}-\d{2}-\d{2}"),
    n, "Order date must use YYYY-MM-DD format"
)

add_check(
    "Date Outside Allowed Range",
    parsed_dates.notna() &
    ((parsed_dates.dt.date < date(2025, 1, 1)) |
     (parsed_dates.dt.date > date.today())),
    n, "Date must be between 2025-01-01 and today"
)

# 4. Allowed category values
add_check(
    "Invalid Customer Segment",
    ~segments.isin(["Student", "Fresher", "Professional"]),
    n, "Segment must be Student, Fresher, or Professional"
)

add_check(
    "Invalid Product Category",
    ~categories.isin(["Learning Kit", "Course Access", "Mentor Session"]),
    n, "Category must match the documented allowed values"
)

# 5. Numeric validity
quantity = pd.to_numeric(df["quantity"], errors="coerce")
unit_price = pd.to_numeric(df["unit_price"], errors="coerce")
discount = pd.to_numeric(df["discount_pct"], errors="coerce")

add_check(
    "Invalid Quantity",
    quantity.isna() | (quantity <= 0),
    n, "Quantity must be a positive number"
)

add_check(
    "Invalid Unit Price",
    unit_price.isna() | (unit_price <= 0),
    n, "Unit price must be positive"
)

add_check(
    "Missing or Invalid Discount",
    discount.isna() | (discount < 0) | (discount > 100),
    n, "Discount must be present and between 0 and 100"
)

# 6. Payment status
add_check(
    "Invalid Payment Status",
    ~payments.isin(["Paid", "Pending"]),
    n, "Payment status must be Paid or Pending"
)

quality_report = pd.DataFrame(checks)

print("DATA QUALITY REPORT")
display(quality_report)

print("\nTOTAL FAILED CHECKS:")
print(int((quality_report["Failed Rows"] > 0).sum()))

print("\nROWS REQUIRING INVESTIGATION:")
display(df[
    df["order_id"].duplicated(keep=False) |
    parsed_dates.isna() |
    discount.isna()
])

DATA QUALITY REPORT

,Quality Check,Failed Rows,Total Rows,Pass Rate (%),Rule
0,Missing Order ID,0,12,100.00,Order ID must not be missing
1,Missing City,1,12,91.67,City must not be empty
2,Duplicate Order ID,2,12,83.33,Order ID must be unique according to the data ...
3,Invalid Date Format or Value,3,12,75.00,Order date must use YYYY-MM-DD format
4,Date Outside Allowed Range,0,12,100.00,Date must be between 2025-01-01 and today
5,Invalid Customer Segment,0,12,100.00,"Segment must be Student, Fresher, or Professional"
6,Invalid Product Category,0,12,100.00,Category must match the documented allowed values
7,Invalid Quantity,2,12,83.33,Quantity must be a positive number
8,Invalid Unit Price,0,12,100.00,Unit price must be positive
9,Missing or Invalid Discount,2,12,83.33,Discount must be present and between 0 and 100
10,Invalid Payment Status,2,12,83.33,Payment status must be Paid or Pending

TOTAL FAILED CHECKS:
6

ROWS REQUIRING INVESTIGATION:

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
6,RT-1006,2026-13-10,Student,Pune,Learning Kit,-1,799,10.0,Paid
11,RT-1011,NaN,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [8]:

# EXPORT DATA QUALITY REPORT

from pathlib import Path

PROJECT_DIR = Path.cwd().parent
deliverables_dir = PROJECT_DIR / "deliverables"
deliverables_dir.mkdir(parents=True, exist_ok=True)

# Save quality-check results
quality_report.to_csv(
    deliverables_dir / "data_quality_report.csv",
    index=False
)

# Save rows requiring investigation
problem_rows = df[
    df["order_id"].duplicated(keep=False) |
    df["city"].isna() |
    parsed_dates.isna() |
    (quantity <= 0) |
    discount.isna() |
    ~payments.isin(["Paid", "Pending"])
]

problem_rows.to_csv(
    deliverables_dir / "rows_requiring_investigation.csv",
    index=False
)

print("Reports saved successfully!")
print("Location:", deliverables_dir)
print("Files created:")
print("- data_quality_report.csv")
print("- rows_requiring_investigation.csv")

Reports saved successfully!
Location: c:\Users\k\Desktop\KPI-Data-Quality-Project\deliverables
Files created:
- data_quality_report.csv
- rows_requiring_investigation.csv